### ISSUE TITLE
Typing Support

### ISSUE THREAD

**Issue by titusfortner** [titusfortner/watir_model#3]
I'm removing the implementation I had in there since I don't like it.

I think it is best to keep Watir Model always using the "key" method, just like Watir Drops uses the "element" method and not confuse it with method missing typing.

That being said, type conversion and/or verification is a useful feature.

Maybe a better implementation would to pass in the parameter as arguments

```
class PubTime < WatirModel
  key(:beer_type, Symbol) { :ipa }
  key(:when, DateTime) { DateTime.now }
  key(:ready, "Boolean") { false }
end

pub_time = PubTIme.new(beer_type: "porter", when: "2016-12-31T16:30:33-06:00", ready: "true")
pub_time.beer_type == :porter
pub_time.when == <DateTime: 2016-12-31T16:30:33-06:00 ((2457754j,81033s,703417000n),-21600s,2299161j)>
pub_time.ready == true
```

If we wanted to get Fancy we could even do this to convert each items in an array to the desired type:
```
key(:nested_stuff, [PubOptionsModel])
```

The other question is whether to raise an exception if the input can not be translated into the desired type, and whether that should be toggled. Which I'm leaning toward yes if it is specified.

**Comment by titusfortner** [comment]
@tk8817 - opinions?

**Comment by titusfortner** [comment]
Released this with 0.3.0, but still interested in thoughts

**Comment by azohra** [comment]
we LOVE this approach. However, to maintain confident code I would heavily lean toward ALWAYS raising an exception for missing/mis-matched types. 

I am not sure I see your vision on a configurable parameter. Could you expand on the flow you are imagining? Are you talking about just making the input a string if you cannot find a type?

**Comment by titusfortner** [comment]
The idea behind DataModel is to always be able to store the data in its "correct" type.

The use case is that I want to get a return from an API call and store it in a model. But results from an API have most values as a String, and a WatirModel shouldn't store things like dates as strings, so if the key value is set to be a DateTime, then converting a JSON to a DataModel instance would `DateTime.parse` the value. Same thing with integers and booleans. It would also help with things that get stored in ENV variables for ConfigModel. :)

**Comment by titusfortner** [comment]
So the second part of that question was if a key is specified to be a DateTime object, but what is passed in as that value is a string that can not be properly parsed into a DateTime object, should it be stored as a String, or raise an exception?

**Comment by titusfortner** [comment]
implemented
